config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  root to: 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post_images, only:[:new,:create,:index,:show]
  resources :users
  resources :books


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
   validates :title,presence: true
   validates :body,presence: true
   validates :body, length: { maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord

belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username,uniqueness: true,presence: true,
            length:{in:2..20}
  validates :introduction,length:{ maximum:50 }

 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

   has_many :books,dependent: :destroy

   attachment :profile_image



 def email_required?
   false
 end
 def email_changed?
   false
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?

 protected
 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
 end

def after_sign_in_path_for(resource)
	flash[:sign_in] ="Signed in successfully."
	user_path(current_user.id)
end

def after_sign_up_path_for(resource)
	flash[:sign_up] ="Welcome! You have signed up successfully."
	user_path(current_user.id)
end

def after_sign_out_path_for(resource)
	flash[:sign_out] ="signed out successfully."
    root_path
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  before_action :authenticate_user!

  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}

    def ensure_correct_user
      @book = Book.find(params[:id])
      if @book.user.id != current_user.id
        redirect_to books_path
      end
    end


  def show
   @book = Book.new
   @book_show = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    flash[:update] = "successfully created.."
    redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if@book.update(book_params)
    flash[:update] = "successfully updated."
    redirect_to book_path(@book.id)
   else
    render :edit
  end
  end

  def destroy
     @book = Book.find(params[:id])
     if@book.destroy
     flash[:destroy] = "successfully destroyed."
     redirect_to books_path
   end
  end

private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

def new
end

def create
end

def index
end

def show
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only:[:show,:create,:index,:edit,:update,:destroy]

  before_action :ensure_correct_user, {only: [:edit, :update]}

  def ensure_correct_user
    if params[:id].to_i != current_user.id
        redirect_to user_path(current_user.id)
    end
  end

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  end

  def create
    @book = Book.new(book_params)
    book.save
    redirect_to book_path(@book_params)
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user =User.find(params[:id])
    if @user.update(user_params)
      flash[:update] = "successfully updated."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
    def user_params
        params.require(:user).permit(:username,:profile_image,:introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
<div class="container">


<div class="row">
<div class="col-md-3 col-md-offset-3">

<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

<div class="alert">
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
</div>

<p>title</p>

<%= f.text_field :title, class: "book_title" %>

<p>body</p>

<%= f.text_field :body, class: "book_body" %>

<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book.id), class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>
</div>
<div class="col-md-3">
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="body">
<div class="container">

<div class="flash">
<%= flash[:destroy] %>
</div>


<div class="alert">
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
            <%= message %> <br>
        <% end %>
    <% end %>
</div>

<div class="row">
 <div class="col-xs-3">
<h1>User info</h1>

 <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %>
<% if @user.id == current_user.id %>


<table class="table">
	<tbody>
	<tr>
		<th>name</th>
		<th><%= @user.username %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	</tr>
   </tbody>
</table>

<div class="row">
<%= link_to '', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>
<% end %>
<h1>New book</h1>

<%= render 'users/new',books: @book %>

</div>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
      </thead>

<% @books.each do |book| %>


   <tbody>
		<tr>
			<td>
<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "user_imageg", fallback: "no_image.jpg" ,size: '40x40'%>

           </td>
           <td>
           	<%= link_to book.title, book_path(book.id), class: "book_#{book.id}"%>
           </td>
           <td>
           	<%= book.body %>
           </td>
           </tr>
       </tbody>

<% end %>

</table>
</div>
</div>
</div>
</div>

app/views/books/new.html.erb
<div class="body">
	<div class="container">

<h1>welcome to
	<span class="glyphicon glyphicon-book">
<strong>Bookers!</strong>
</span>
</h1>




</div>
</div>

app/views/books/show.html.erb
<div class="body">

<div class="container">

<div class="flash">
<%= flash[:notice] %>
</div>

<div class="flash">
<%= flash[:update] %>
</div>


<div class="row">
<div class="col-xs-3">

<h1>User info</h1>

 <%= attachment_image_tag @book_show.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %>


<table class="table">
	<tbody>
	<tr>
		<th>name</th>
		<th><%= @book_show.user.username %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= @book_show.user.introduction %></th>
	</tr>
   </tbody>
</table>

<div class="row">
<%= link_to '', edit_user_path(@book_show.user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@book_show.user.id}" %>
</div>

<h1>New book</h1>

<%= render 'users/new',books: @book %>

</div>

<div class="col-xs-9">
<h1>Book detail</h1>

<table class="table">

  <tbody>
		<tr>
			<td>
<%= attachment_image_tag @book_show.user, :profile_image, :fill, 10, 10, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %><br>

          <%= link_to @book_show.user.username, user_path(@book_show.user), class: "books" %>
           </td>
           <td>
           	<%= @book_show.title %>
           </td>
           <td>
           	<%= @book_show.body %>
           </td>
           <td>
            <% if @book_show.user_id == current_user.id %>
             	<%= link_to "Edit", edit_book_path(@book_show.id), class: "btn-sm btn-success edit_book_#{@book_show.id}" %>
             </td>
             <td>
               <%= link_to "Destroy", book_path, method: :delete,"data-confirm" => "本当に消しますか？", class: "btn-sm btn-danger destroy_book_#{@book_show.id}" %>
             </td>
           <% end %>

       </tr>
   </tbody>

</table>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<header class="navbar navbar-fixed-top navbar-inverse" style="background-color:black;">
  <div class="container">
  <nav class="nav navbar-nav navbar-left" style="color:white;">
    <span>Bookers</span>
  </nav>
  <nav>
    <ul class="nav navbar-nav navbar-right" style="list-style:none;">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "glyphicon glyphicon-user users" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books" %>
      </li>
      <li class="nav-item">
        <%= link_to 'logout',  destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", new_book_path, class: "glyphicon glyphicon-link about about" %>
      </li>
      <li class="nav-item">
        <%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
      </li>
      <li class="nav-item">
        <%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
      </li>
    <% end %>
  </ul>
</nav>
</header>

  </footer>
  </body>

    <%= yield %>
    <footer class="footer">
    <div class="container">
    <p class="col-md-6 col-md-offset-3" >
            <div class= "text-align-right">
         CopyRight Infratop.inc</p>
         </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_new.html.erb
<%= form_for(@book) do |f| %>


<h4>Title</h4>
<%= f.text_field :title , class: "book_title" %>


<h4>Opinion</h4>
<%= f.text_area :body , class: "book_body" %><br>

<%= f.submit 'Create Book' %>


<% end %>

app/views/users/edit.html.erb
<div class="body">
	<div class="container">




<h1>User info</h1>

<%= form_for(@user) do |f| %>

<div class="alert">
<% if @user.errors.any? %>
<%= @user.errors.count %>error prohibited this obj from being saved:<br>
        <% @user.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
</div>




<div class="field">
	<label for="user_name">Name</label>
<%= f.text_field :username, class: "name" %>
</div>
<div class="field">
<label for="user_image">Image</label>
<%= f.attachment_field :profile_image, class: "user_image" %>
</div>
<div class="field">
	<label for="user_introduction">Introduction</label>
<%= f.text_field :introduction, class: "introduction" %>
</div>



<%= f.submit "Update User" %>

<% end %>

</div>
</div>

app/views/users/index.html.erb
<div class="body">
<div class="container">



<div class="row">
	<div class="col-xs-3">
<h1>User info</h1>

 <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %>
<% if @user.id == current_user.id %>
<% end %>

<table class="table">
	<tbody>
	<tr>
		<th>name</th>
		<th><%= @user.username %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	</tr>
   </tbody>
</table>

<%= link_to '', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>

<h1>New book</h1>

<%= render 'users/new',users: @user %>
</div>

<div class="col-xs-9">
<h1>Users</h1>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>

<% @users.each do |user| %>
       <tbody>
		<tr>
			<td>

<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "user_image", fallback: "no_image.jpg",size: '40x40' %>
<% if @user.id == current_user.id %>
<% end %>
           </td>
           <td>
           	<%= user.username %>
           </td>
           <td>
           	<%= link_to "show", user_path(user.id), class: "user_#{user.id}" %>
           </td>
           </tr>
       </tbody>
<% end %>
</table>
</div>
</div>

app/views/users/show.html.erb
<div class="body">
<div class="container">

<div class="flash">
<%= flash[:notice] %>
</div>

<div class="flash">
<%= flash[:update] %>
</div>





<div class="row">
<div class="col-xs-3">
<h1>User info</h1>

 <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %>


<table class="table">
	<tbody>
	<tr>
		<th>name</th>
		<th><%= @user.username %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	</tr>
   </tbody>
</table>

<div class="row">
<%= link_to "", edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %>
</div>
<h1>New book</h1>

<%= render 'users/new',users: @user %>
</div>


<div class="col-xs-9">
<h1>Books</h1>


<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
	</thead>

	<% @user.books.each do |book| %>

	<tbody>
		<tr>
			<td>
<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "user_image", fallback: "no_image.jpg", size: '40x40' %>
           </td>
           <td>
           	<%= link_to book.title, book_path(book.id), class: "book_#{book.id}"%>
           </td>
           <td>
           	<%= book.body %>
           </td>
           </tr>
       </tbody>

<% end %>

</table>
</div>

app/views/users/top.html.erb
<div class="body">
<div class="container">

<div class="flash">
<%= flash[:notice] %>
</div>



<div class="row">

<div class="top-message col-md-offset-3 col-md-6">

<h1>welcome to <span class="glyphicon glyphicon-book">
<strong>Bookers!!</strong>
</span>
</h1>

<p>In
	<span class="glyphicon glyphicon-book"></span>
 <strong>Bookers,</strong>
 </p>

 <p>you can share and exchange your opinions , inpressions , and emotions</p>

 <p>about varioius books!</p>

<div class="btn-wrapper">
	<div class="row">
<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %>
</div>
   <div class="row">
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
</div>
</div>
</div>
</div>
</div>